language: generic

sudo: required

services:
  - docker

defore_install:
  - docker build -t rkdalstjd9/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true rkdalstjd9/react-test-app npm run test

after_success:
  - docker build -t rkdalstjd9/docker-frontend ./frontend
  - docker build -t rkdalstjd9/docker-backend ./backend
  - docker build -t rkdalstjd9/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push rkdalstjd9/docker-frontend
  - docker push rkdalstjd9/docker-backend
  - docker push rkdalstjd9/docker-nginx

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-569101977538"
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY